Feature/data config UI sequence change
abasatwar/observability pull request #15
Opened 2022-06-29 05:57 UTC by deepaknevdepsl

### Description
Sequence of Metrics and Dimensions changes
https://github.com/opensearch-project/observability/issues/787

### Issues Resolved
[List any issues this PR will resolve]

### Check List
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-06-29 14:21 UTC, abasatwar requested changes

2022-06-29 14:21 UTC, abasatwar commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_item.tsx
> +};
add new line at the end

2022-06-30 05:16 UTC, deepaknevdepsl commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_item.tsx
> +};
Added new line at the end.

2022-07-07 14:26 UTC, abasatwar approved these changes

2022-07-11 10:16 UTC, merged