Feature/cypress test case heatmap
abasatwar/observability pull request #26
Opened 2022-07-04 12:50 UTC by nidhisinghai

Cypress test case for heatmap data configuration panel are created

@abasatwar @spattnaik

2022-07-08 09:41 UTC, abasatwar requested changes

2022-07-08 09:41 UTC, abasatwar commented on dashboards-observability/.cypress/integration/1_event_analytics.spec.js
> +});
add empty line

2022-07-08 10:27 UTC, spattnaik approved these changes

2022-07-11 10:19 UTC, nidhisinghai commented on dashboards-observability/.cypress/integration/1_event_analytics.spec.js
> +});
done

2022-08-12 13:46 UTC, nidhisinghai commented
closing this, as created a separate individual files for each chart

2022-08-12 13:46 UTC, closed without merging