Pie chart enhancement, multi labels change
abasatwar/observability pull request #28
Opened 2022-07-05 12:02 UTC by deepaknevdepsl

### Description
Pie chart enhancement https://github.com/opensearch-project/observability/issues/833

### Issues Resolved
[List any issues this PR will resolve]

### Check List
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-05 14:00 UTC, spattnaik requested changes

2022-07-05 14:00 UTC, spattnaik commented on dashboards-observability/public/components/visualizations/charts/pie/pie.tsx
> +    return dimLabels.map((label, index) => {
label can be a string and index a number

2022-07-05 14:00 UTC, spattnaik commented on dashboards-observability/public/components/visualizations/charts/pie/pie.tsx
> +  const createLegendLabels = (dimLabels: any[], xaxisLables: { [x: string]: any; }) => {
as labels are strings, instead of defining dimLabels as array of any, can we define array of strings? Same goes with xaxisLabels as well, instead of the values being any, we can define as string? Let me know, if I am incorrect.

2022-07-05 14:00 UTC, spattnaik commented on dashboards-observability/public/components/visualizations/charts/pie/pie.tsx
> +        dimLabelsArray = createLegendLabels(dimLabelsArray, data[xaxis[i + 1].label]);
This `dimLabelsArray` is getting overwritten inside the for loop several times. After the loop ends, you will have access to the last iteration value only. If you need only the last one, you could have just accessed it using the last index.

2022-07-06 07:47 UTC, deepaknevdepsl commented on dashboards-observability/public/components/visualizations/charts/pie/pie.tsx
> +    return dimLabels.map((label, index) => {
Added type to label and index

2022-07-06 07:48 UTC, deepaknevdepsl commented on dashboards-observability/public/components/visualizations/charts/pie/pie.tsx
> +  const createLegendLabels = (dimLabels: any[], xaxisLables: { [x: string]: any; }) => {
Added types for above variables

2022-07-06 12:08 UTC, spattnaik approved these changes

2022-07-11 12:41 UTC, merged