Horizontal bar chart implimentation
abasatwar/observability pull request #51
Opened 2022-07-25 12:41 UTC by deepaknevdepsl

### Description
Added Horizontal Bar chart as a new visualization  type.

### Issues Resolved
#885

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-27 10:34 UTC, abasatwar requested changes

2022-07-27 10:34 UTC, abasatwar commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panel.tsx
>    const memorizedVisualizationTypes = useMemo(() => {
can we avoid usememo here?

2022-07-27 10:34 UTC, abasatwar commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panel.tsx
> +        visDefinition = vs === visChartTypes.Bar ? getVisType(vs, { type: visChartTypes.Bar }) : getVisType(vs, { type: visChartTypes.HorizontalBar });
check the formatting of all files and lint errors too if any.

2022-07-27 12:09 UTC, deepaknevdepsl commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panel.tsx
>    const memorizedVisualizationTypes = useMemo(() => {
No, as we are using memorized data here.

2022-07-27 12:09 UTC, deepaknevdepsl commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panel.tsx
> +        visDefinition = vs === visChartTypes.Bar ? getVisType(vs, { type: visChartTypes.Bar }) : getVisType(vs, { type: visChartTypes.HorizontalBar });
formatted files and pushed.

2022-08-12 13:44 UTC, abasatwar commented
https://github.com/opensearch-project/observability/pull/924 - is raised for this functionality

2022-08-12 13:44 UTC, closed without merging